### ISSUE TITLE
Add documentation for Safe recovery and draining

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-cli#107]
# What is needed?
- Documentation to deploy a Safe in other network and send all the funds to another address

# Background
https://help.gnosis-safe.io/en/articles/5267779-i-sent-assets-to-a-safe-address-on-the-wrong-network-any-chance-to-recover

**Comment by moisses89** [comment]
@Uxio0 the purpose of this issue is now document how to recovery a Safe with `safe-creator`, migrate to L2 if is necessary or drain.

**Comment by JagoFigueroa** [comment]
Looks good to me!
