### ISSUE TITLE
Support Trezor for signing

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-cli#270]
# What is needed?
Trezor must be supported for signing

**Comment by wminshew** [comment]
So if I have a safe on OP from proxy-factory `0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2` (not supported by UI) with only trezor signers, do I have any workaround options today to execute txns?

**Comment by LayneHaber** [comment]
any idea when trezor support will be added here?

**Comment by Uxio0** [comment]
@LayneHaber We are working on it as you can see in the linked PR, it should be ready next week 😉

**Comment by JagoFigueroa** [comment]
Tested and verified, reported a couple of small issues that will be tackled on separate tickets 😄
