### ISSUE TITLE
Add migration upgrade from non L2 Safes to L2 Safes  

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-cli#285]
# What is needed?
Add command or include in upgrade command, support to migrate a non L2 Safe to L2 Safe 

# Related issues
https://github.com/safe-global/safe-transaction-service/issues/1703

**Comment by Uxio0** [comment]
@JagoFigueroa we require QA on this 🙏🏻 . The way to test it would be to deploy a Safe v1.1.1 and v1.3.0 (not L2) on Polygon, use the command `update_to_l2 0x1Ba30910CE8Eb45b276aa7c89C38FC52228B85CB` (that's the address for the not official migration contract in Polygon deployed by me) and then use the Safe with our official UI and check transactions show as expected

**Comment by JagoFigueroa** [comment]
Hola team! Working nicely for me, I updated 2 safes on Polygon [one](https://app.safe.global/transactions/history?safe=matic:0x24dEd3ed2eB894665AEB8838C83BfB614Ba0Db2C) from 1.1.1 and [another](https://app.safe.global/transactions/history?safe=matic:0x881C09aA91616ca31D07834940Db8823fBEE3E64) from 1.3.0 and was able to transact with them without any issues once updated from the CLI. Also tried tx-service mode and was able to update on UI from the queue.

Cheers!

**Comment by Uxio0** [comment]
Thank you very much, I understand this feature was not easy to test!
