### ISSUE TITLE
Duplicated ledger accounts with the same address and derivation path

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-cli#302]
**Describe the bug**
Two instances of LedgerAccount with the same attributes are currently evaluated as different, leading to duplication in the LedgerManager.accounts set.
```
In [12]: LedgerAccount("44'/60'/0'/0/10", 0x85bC4dc18e2Dde71294EA1c87CF0824A4c04489D) == LedgerAccount("44'/60'/0'/0/10", 0x85bC4dc18e2Dde71294EA1c87CF0824A4c04489D)
Out[12]: False
```

**Comment by moisses89** [comment]
Work in progress here https://github.com/mikeshultz/ledger-eth-lib/pull/51

**Comment by JagoFigueroa** [comment]
Tested and verified! ✅
