### ISSUE TITLE
Delete proposed not executed transactions 

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-cli#306]
# What is needed?
Add command to delete proposed not executed transactions, related to https://github.com/safe-global/safe-transaction-service/issues/1757

**Comment by moisses89** [comment]
Issue is blocked until close https://github.com/safe-global/safe-transaction-service/issues/1757

**Comment by JagoFigueroa** [comment]
The feature is working nicely. Thanks! We reported a couple of separate issues but we can continue with those on separate tickets 🙇

**Comment by Uxio0** [comment]
Like an hydra @JagoFigueroa , any time we cut a head we get two new ones

**Comment by JagoFigueroa** [comment]
Kratos approves! 😆 

![panardo](https://github.com/safe-global/safe-cli/assets/92332710/2edd7e1d-540a-49ab-834e-6f9aab491ec6)
