### ISSUE TITLE
Make the CLI more inclusive

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-cli#319]
Analyze and implement if necesary recommendations from: https://seirdy.one/posts/2022/06/10/cli-best-practices/

**Comment by falvaradorodriguez** [comment]
After review and discussion with the team, the actions to be taken are:

- Improve the usage message when executing the --help command. Add usage examples.
- Add --version option in the safe-cli and safe-creator commands to improve debugging.
- Add message to be more user friendly once the safe information is listed.
- Add a help subcommand to list all options inside a safe.
- Add an exit subcommand to end the execution of safe-cli.
