### ISSUE TITLE
Trezor support uses wrong derivation paths

### ISSUE THREAD

**Issue by aspiers** [safe-global/safe-cli#331]
**Describe the bug**
When using the latest git code with Trezor support added in #318 to attempt to execute safe transactions via my Ledger Model T, I see the CLI using derivation paths which don't match my Ethereum addresses.

**To Reproduce**
1. Install via `pip3 install --user git+https://github.com/safe-global/safe-cli` and `pip3 install safe-cli[trezor]`
2. Run `safe-cli`
3. Run `load_trezor_cli_owners` with no parameters
4. Observe the following output

       0 - ('<censored>, "44'/60'/0'/0/0")
       1 - ('<censored>, "44'/60'/1'/0/0")
       2 - ('<censored>, "44'/60'/2'/0/0")
       3 - ('<censored>, "44'/60'/3'/0/0")
       4 - ('<censored>, "44'/60'/4'/0/0")

   In this output, the first address for `44'/60'/0'/0/0` is correct, but all the others do not match the addresses of my other wallets.
5. Run `load_trezor_cli_owners --derivation-path 44'/60'/0'/0/1`
6. Observe that the output now indicates that my second wallet has been correctly selected.
7. Repeat for `44'/60'/0'/0/2` and confirm this also correctly yields the third wallet.

**Expected behavior**
`load_trezor_cli_owners` with no parameters should iterate via `44'/60'/0'/0/i` rather than `44'/60'/i'/0/0`.

**Additional context**

Use of `44'/60'/0'/0/i` aligns correctly with the derivation path documented in Trezor's official docs:

- https://docs.trezor.io/trezor-firmware/misc/coins-bip44-paths.html#list-of-used-derivation-paths

**Comment by JagoFigueroa** [comment]
Thanks for reporting this! Issue should be resolved now 😄
