### ISSUE TITLE
CLI session closed when using a derivation path with "" or '' with Trezor hardware wallet

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-cli#343]
**Describe the bug**
Small issue where the CLI will crash when either `""` or `''` are used when trying to load an address from a derivation path on Trezor.

**To Reproduce**
Example command:
````
load_trezor_cli_owners --legacy-accounts --derivation-path "44'/60'/0'/0"
````

**Expected behavior**
Return an error, same as with ledger:
```
load_ledger_cli_owners --legacy-accounts --derivation-path "44'/60'/0'/0"
HwDevice exception: The provided derivation path is not valid
```
**Current behaviour**
The CLI crashes

**Comment by moisses89** [comment]
The CLI is not crashing but I'm still adding support for double quoting because looks like the natural behavior of an user.
#414

**Comment by JagoFigueroa** [comment]
Working like a charm, thank you caballero
