### ISSUE TITLE
CLI session closed when trying to sign_message via a hardware wallet on tx-service mode

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-cli#344]
**Describe the bug**
Currently it is not possible to sign_message via a hardware wallet on tx-service mode. After talking with the devs this looks to be expected for now but we have an issue where the CLI terminates the current session  after trying to do so.

**To Reproduce**
Via tx-service mode, try to sign_message:
```
tx-service > 0x4E24f2497445125C4573f7935ADeDEce154317b8 > sign_message --eip191_message I_love_Doritos
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/safe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
...
 /safe_tx_service_operator.py", line 68, in sign_message
    raise NotImplementedError("SignHash by hardware wallet is not implemented")
NotImplementedError: SignHash by hardware wallet is not implemented
(venv)user safe-cli % 

```
**Expected behavior**
Throw an error without interrupting the session

**Actual behavior**
CLI session is closed

**Comment by Uxio0** [comment]
@moisses89 were you able to fix it?

**Comment by moisses89** [comment]
The last version is catching the error correctly:
```
tx-service > 0xf5951F6b664819ddbA656Ab228fbb8E8f5A1c3 > sign_message --eip191_message I_love_doritos
Signing messages is not currently supported by hardware wallets
tx-service > 0xf5951F6b664819DdbA656Ab228fbb8E8f5A1c3 > 
```

**Comment by moisses89** [comment]
@JagoFigueroa could you confirm if the last released version fix the issue?

**Comment by JagoFigueroa** [comment]
I can confirm that an error is now shown for both Ledger and Trezor wallets when trying to sign a 712 or 191 message on tx-service mode.

Un saludito cracks 😉
