### ISSUE TITLE
Error loading owners on opBNB: "Cannot find enough owners to sign. 1 missing"

### ISSUE THREAD

**Issue by louis-md** [safe-global/safe-cli#381]
**Describe the bug**

On opBNB, there seems to be issues to correctly load owners.

**Expected behavior**

Load correctly all owners for this network.

**Additional context**

More context about the problem [here](https://ethereum.stackexchange.com/questions/161746/cannot-find-enough-owners-to-sign-1-missing/161863) and [here (internal)](https://5afe.slack.com/archives/C049H57FS1E/p1711381678604299)

**Comment by Uxio0** [comment]
The Safe they are trying to load is not a valid Safe contract
