### ISSUE TITLE
[DOC] Adding scripting mode documentation to safe-docs

### ISSUE THREAD

**Issue by falvaradorodriguez** [safe-global/safe-cli#434]
The new options implemented in https://github.com/safe-global/safe-cli/issues/36 need to be added to the `safe-cli` documentation in `safe-docs`. 

Currently only the interactive mode is documented, and the direct commands as well as the `tx-builder` command need to be documented.

**Comment by sebastiendan** [comment]
Hey @falvaradorodriguez, any chance I could get some guidelines for `tx-builder` while the doc is being worked on? I couldn't find details regarding the file that the command expects (what it should contain, etc.).

**Comment by falvaradorodriguez** [comment]
> Hey @falvaradorodriguez, any chance I could get some guidelines for `tx-builder` while the doc is being worked on? I couldn't find details regarding the file that the command expects (what it should contain, etc.).

Hi @sebastiendan, you can generate and export one of these JSON files from the `Transaction Builder` app on the Safe website. 

![Screenshot 2024-07-16 at 16 22 45](https://github.com/user-attachments/assets/a4b4d5ff-643e-4d42-bd64-f76b00230654)

**Comment by sebastiendan** [comment]
@falvaradorodriguez So you mean the `tx-builder` command is not a replacement for the UI, but a complementing tool? (basically I'm looking for a way with `safe-cli` to create and propose a transaction, for it to be later multisig-ed in Safe Wallet)

**Comment by falvaradorodriguez** [comment]
> @falvaradorodriguez So you mean the `tx-builder` command is not a replacement for the UI, but a complementing tool? (basically I'm looking for a way with `safe-cli` to create and propose a transaction, for it to be later multisig-ed in Safe Wallet)

Sorry, I didn't express myself well. Yes, `safe-cli` replaces the interface. What I meant to say was that you could generate a JSON example from there as we don't have documentation on how to generate it at the moment.

Anyway, if you are looking to propose a transaction, [this](https://docs.safe.global/advanced/cli-reference/common-commands#transactions) may help.

Even [here](https://github.com/safe-global/safe-cli?tab=readme-ov-file#safe-cli-1) shows some examples of how to directly use the commands to create and propose a transaction.

**Comment by sebastiendan** [comment]
@falvaradorodriguez I've run some tests, and from what I can see `send-custom` requires all signers (it basically propose, confirm, and execute all at once).

**Comment by falvaradorodriguez** [comment]
@sebastiendan Yes, if you are only looking to propose the transaction, for the moment, from `safe-cli` it's only possible to do the complete flow (as the main idea is to be a substitute for the interface). 

Anyway, you could propose the transaction using the SDK from Python or Js following this [example](https://docs.safe.global/core-api/transaction-service-guides/transactions#send-the-transaction-to-the-service).

As this topic already differs from the initial question, if you still have doubts about this, it might be better to move the question to the appropriate channel. Thanks in advance.
