### ISSUE TITLE
Deploy ZKSync networks, Zerion, Zero Network Testnet

### ISSUE THREAD

**Issue by alfredolopez80** [safe-global/safe-cli#458]
# Issue Report for Safe Creator

## Chain ID
Chain_ID: 4457845

## RPC URL
RPC_URL: https://rpc.zerion.io/v1/zero-sepolia

## Relevant Information
Network based on ZkSync Stack
safe-singleton-factory issue: [New chain]: Zero Network Testnet safe-singleton-factory#845  
Explorer: https://explorer.zero.network

---

# What is needed?
I encountered an error while trying to create a new Safe using the Safe Creator tool. The process fails with an `AttributeError` related to the `SignedTransaction` object.

# Background
When attempting to deploy a new Safe on the Zero Network Testnet, the Safe Creator tool throws an error indicating that the `SignedTransaction` object does not have the attribute `rawTransaction`. This seems to be a potential bug in the code where the attribute name might be incorrectly referenced.

# Related Issues
command executed:
```bash
safe-creator https://rpc.zerion.io/v1/zero-sepolia {PK of wallet 0x562B9F0dfd46901d7b1E70414625C27d257076E5} --threshold 1 --owners 0x562B9F0dfd46901d7b1E70414625C27d257076E5 0xd41014BDA7680abE19034CbDA78b3807e51Ff2e8 0x658B13b773b0ceD400eC57cf7C03288d8Aa13805 0xA886C0c3AacdeA26ae29fB7eE6056874e6128622 0x0A95f5441dE95716154A7b8b8C60E0a0260Ac964 --safe-contract 0x1727c2c531cf966f902E5927b98490fDFb3b2b70 --proxy-factory 0xDAec33641865E4651fB43181C6DB6f7232Ee91c2 --callback-handler 0x2f870a80647BbC554F3a0EBD093f11B4d2a7492A
```
Faucet: https://docs.zero.network/build-on-zero/testnet-faucets (can use the bridge from ethereum-sepolia, or claim directly of faucet, the best and more quickly option is the bridge).
docs: https://docs.zero.network/

# Endpoint
The issue occurs during the transaction sending process in the Safe Creator tool.

## URL
N/A

## Response
The following error message is returned:

```bash
/Users/alfredolopez/.pyenv/versions/3.12.3/lib/python3.12/site-packages/web3/eth/eth.py:186: UserWarning: There was an issue with the method eth_maxPriorityFeePerGas. Calculating using eth_feeHistory.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/alfredolopez/.pyenv/versions/3.12.3/bin/safe-creator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/alfredolopez/.pyenv/versions/3.12.3/lib/python3.12/site-packages/safe_cli/safe_creator.py", line 220, in main
    ethereum_tx_sent = proxy_factory.deploy_proxy_contract_with_nonce(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alfredolopez/.pyenv/versions/3.12.3/lib/python3.12/site-packages/gnosis/safe/proxy_factory.py", line 253, in deploy_proxy_contract_with_nonce
    return self._deploy_proxy_contract(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alfredolopez/.pyenv/versions/3.12.3/lib/python3.12/site-packages/gnosis/safe/proxy_factory.py", line 150, in _deploy_proxy_contract
    tx_hash = self.ethereum_client.send_unsigned_transaction(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alfredolopez/.pyenv/versions/3.12.3/lib/python3.12/site-packages/gnosis/eth/ethereum_client.py", line 1886, in send_unsigned_transaction
    return self.send_raw_transaction(signed_tx.rawTransaction)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SignedTransaction' object has no attribute 'rawTransaction'. Did you mean: 'raw_transaction'?
```

**Comment by Uxio0** [comment]
We have just released a new version of the service, could you check if you can reproduce? https://github.com/safe-global/safe-cli/releases/tag/v1.4.0

**Comment by alfredolopez80** [comment]
yeah, my partner test with docker and works, i think is a problem with M1 proccessor!!

**Comment by Uxio0** [comment]
Good to hear, thanks for reporting @alfredolopez80
