### ISSUE TITLE
Error is thrown when calling migrate function of l2_migration_contract contract

### ISSUE THREAD

**Issue by patidarmanoj10** [safe-global/safe-cli#471]
**Describe the bug**
`migrateFromV111` and `migrateToL2` method of `l2_migration_contract` contract take single input but deployment [module](https://github.com/safe-global/safe-eth-py/blob/8faba69cc4f0f2bc8b2075129119335eb4dd8e84/safe_eth/safe/safe_deployments.py#L1702-L1704)  is returns array . Method call fails because of method params type mismatch. 

Below lines of code return array of addresses 
```
safe_l2_singleton = safe_deployments["1.3.0"]["GnosisSafeL2"][str(chain_id)]
```
This array is passed in `l2_migration_contract.functions.migrateFromV111()` and `l2_migration_contract.functions.migrateToL2()` which is wrong because migration contract expecting only one address not array.

Deployment address is read from [here](https://github.com/safe-global/safe-eth-py/blob/8faba69cc4f0f2bc8b2075129119335eb4dd8e84/safe_eth/safe/safe_deployments.py#L1702-L1704) . This returns array of 2.

**Expected behavior**
Pick only one address from array and pass to method call. Example PR here 
Please check PR created for this fix. https://github.com/safe-global/safe-cli/pull/465/files 

Not sure if which index address should be used but atleast I know it should be one input when calling method of migration contract

**Additional context**

cc @Uxio0

**Comment by Uxio0** [comment]
This will be fixed by https://github.com/safe-global/safe-cli/pull/470

**Comment by Uxio0** [comment]
Thank you for reporting!
